{% set name = "nvim" %}
{% set version = "0.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/neovim/neovim/archive/v{{ version }}.tar.gz
  sha256: 06b8518bad4237a28a67a4fbc16ec32581f35f216b27f4c98347acee7f5fb369

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
    - make
    - pkg-config
  host:
    - gettext
    - libiconv  # [osx]
    - libmpack-lua
    - libtermkey
    - libuv
    - libvterm
    - lua-lpeg
    - luajit-openresty
    - luv
    - msgpack-c
    - libtree-sitter
    - unibilium
  run:
    - gettext
    - libiconv  # [osx]
    - libmpack-lua
    - libtermkey
    - libuv
    - libvterm
    - lua-lpeg
    - luajit-openresty
    - luv
    - msgpack-c
    - libtree-sitter
    - unibilium

test:
  commands:
    - nvim --version

about:
  home: https://neovim.io/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: Ambitious Vim-fork focused on extensibility and agility
  dev_url: https://github.com/neovim/neovim

extra:
  recipe-maintainers:
    - danielnachun
