{% set name = "nvim" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/neovim/neovim/archive/v{{ version }}.tar.gz
  sha256: 372ea2584b0ea2a5a765844d95206bda9e4a57eaa1a2412a9a0726bab750f828

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cmake
    - make
    - pkg-config
    - gettext  # [build_platform != target_platform]
    - libiconv  # [osx]
    - libmpack-lua  # [build_platform != target_platform]
    - libtree-sitter  # [build_platform != target_platform]
    - libuv  # [build_platform != target_platform]
    - libvterm  # [build_platform != target_platform]
    - lua-lpeg  # [build_platform != target_platform]
    - luajit-openresty  # [build_platform != target_platform]
    - luv  # [build_platform != target_platform]
    - msgpack-c  # [build_platform != target_platform]
    - unibilium  # [build_platform != target_platform]
  host:
    - gettext
    - libiconv  # [osx]
    - libmpack-lua
    - libtermkey
    - libtree-sitter
    - libuv
    - libvterm
    - lua-lpeg
    - luajit-openresty
    - luv
    - msgpack-c
    - unibilium
  run:
    - gettext
    - libiconv  # [osx]
    - libmpack-lua
    - libtermkey
    - libtree-sitter
    - libuv
    - libvterm
    - lua-lpeg
    - luajit-openresty
    - luv
    - msgpack-c
    - unibilium

test:
  commands:
    - nvim --version

about:
  home: https://neovim.io/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: Ambitious Vim-fork focused on extensibility and agility
  dev_url: https://github.com/neovim/neovim

extra:
  recipe-maintainers:
    - danielnachun
    - anjos
