{% set name = "nvim" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/neovim/neovim/archive/v{{ version }}.tar.gz
  sha256: 39d79107c54d2f3babcad2cd157c399241c04f6e75e98c18e8afaf2bb5e82937

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
    - make
    - pkg-config
  host:
    - gettext
    - libiconv  # [osx]
    - libmpack-lua
    - libtermkey
    - libuv
    - libvterm
    - lua-lpeg
    - luajit-openresty
    - luv
    - msgpack-c
    - libtree-sitter
    - unibilium
  run:
    - gettext
    - libiconv  # [osx]
    - libmpack-lua
    - libtermkey
    - libuv
    - libvterm
    - lua-lpeg
    - luajit-openresty
    - luv
    - msgpack-c
    - libtree-sitter
    - unibilium

test:
  commands:
    - nvim --version

about:
  home: https://neovim.io/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: Ambitious Vim-fork focused on extensibility and agility
  dev_url: https://github.com/neovim/neovim

extra:
  recipe-maintainers:
    - danielnachun
